"use client"

import { Droplets, Layers, Map } from "lucide-react"
import { Panel } from "@/components/farm/panel"
import { cn } from "@/lib/utils"
import { formatWaterLitres, statusColors, type Zone, type ZoneId } from "@/lib/irrigation-data"

interface Props { zones: Zone[]; selectedZoneId: ZoneId; onSelectZone: (zoneId: ZoneId) => void; isLoading?: boolean }
const shapes: Array<{ id: Exclude<ZoneId, "NM">; label: string; path: string; x: number; y: number }> = [
  { id: "P1E", label: "PLOT 1\nEAST", path: "M 8 10 L 37 10 L 37 35 L 8 35 Z", x: 22.5, y: 22.5 },
  { id: "P1W", label: "PLOT 1\nWEST", path: "M 8 45 L 37 45 L 37 70 L 8 70 Z", x: 22.5, y: 57.5 },
  { id: "P2E", label: "PLOT 2\nEAST", path: "M 63 10 L 92 10 L 92 35 L 63 35 Z", x: 77.5, y: 22.5 },
  { id: "P2W", label: "PLOT 2\nWEST", path: "M 63 45 L 92 45 L 92 70 L 63 70 Z", x: 77.5, y: 57.5 },
  { id: "JF", label: "JACKFRUIT", path: "M 38 76 L 62 76 L 62 92 L 38 92 Z", x: 50, y: 84 },
]
function getZone(zones: Zone[], id: ZoneId): Zone { return zones.find((zone) => zone.id === id) ?? zones[0] }

export function IrrigationMapWithDetails({ zones, selectedZoneId, onSelectZone, isLoading = false }: Props) {
  const selectedZone = getZone(zones, selectedZoneId)
  return <div className="grid gap-6 lg:grid-cols-3"><div className="lg:col-span-2"><Panel title="Farm Irrigation Map" icon={Map} headerRight={<span className="text-xs text-muted-foreground">Nutmeg overlay: P1E + P2W</span>}>
    {isLoading ? <div className="flex h-[420px] items-center justify-center rounded-lg border border-dashed border-border text-sm text-muted-foreground">Loading live irrigation map...</div> : <div className="overflow-hidden rounded-lg border border-border bg-gradient-to-br from-slate-50 to-emerald-50"><svg viewBox="0 0 100 100" className="h-auto min-h-[320px] w-full max-w-full" role="img" aria-label="MFMS irrigation zone map with Nutmeg overlay"><defs><pattern id="irrigation-grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="#dbeafe" strokeWidth="0.25" /></pattern><pattern id="nutmeg-hatch" patternUnits="userSpaceOnUse" width="2" height="2"><path d="M -0.5,0.5 l 1,-1 M 0,2 l 2,-2 M 1.5,2.5 l 1,-1" stroke="#be185d" strokeWidth="0.35" opacity="0.7" /></pattern></defs><rect width="100" height="100" fill="url(#irrigation-grid)" />{shapes.map((shape) => { const zone = getZone(zones, shape.id); const selected = selectedZoneId === shape.id; const nutmegSelected = selectedZoneId === "NM" && (shape.id === "P1E" || shape.id === "P2W"); const colour = statusColors[zone.status].svg; return <g key={shape.id}><path d={shape.path} fill={colour} fillOpacity={selected || nutmegSelected ? 0.36 : 0.15} stroke={selected || nutmegSelected ? "#0f172a" : colour} strokeWidth={selected || nutmegSelected ? 1.8 : 1.2} className="cursor-pointer transition-all hover:fill-opacity-30" onClick={() => onSelectZone(shape.id)} />{shape.label.split("\n").map((line, index) => <text key={line} x={shape.x} y={shape.y + (index - 0.5) * 4} fontSize="3" fontWeight="700" fill="#0f172a" textAnchor="middle" dominantBaseline="middle" className="pointer-events-none">{line}</text>)}</g> })}<g onClick={() => onSelectZone("NM")} className="cursor-pointer"><path d="M 14 15 L 31 15 L 31 30 L 14 30 Z" fill="url(#nutmeg-hatch)" stroke={selectedZoneId === "NM" ? "#be185d" : "#db2777"} strokeWidth={selectedZoneId === "NM" ? 1.7 : 0.9} strokeDasharray="2 1" opacity={selectedZoneId === "NM" ? 0.95 : 0.45} /><path d="M 69 50 L 86 50 L 86 65 L 69 65 Z" fill="url(#nutmeg-hatch)" stroke={selectedZoneId === "NM" ? "#be185d" : "#db2777"} strokeWidth={selectedZoneId === "NM" ? 1.7 : 0.9} strokeDasharray="2 1" opacity={selectedZoneId === "NM" ? 0.95 : 0.45} /><text x="22.5" y="22.5" fontSize="3" fontWeight="800" fill="#9d174d" textAnchor="middle" dominantBaseline="middle" className="pointer-events-none">NM</text><text x="77.5" y="57.5" fontSize="3" fontWeight="800" fill="#9d174d" textAnchor="middle" dominantBaseline="middle" className="pointer-events-none">NM</text></g><text x="3" y="97" fontSize="2.4" fill="#334155" className="pointer-events-none">Green=Irrigated | Grey=No Record | Hatched=Nutmeg overlay</text></svg></div>}
  </Panel></div><Panel title="Selected Zone Details" icon={Droplets}><div className="space-y-4"><div className="rounded-xl border border-border bg-muted/20 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{selectedZone.abbr}</div><div className="mt-1 text-xl font-extrabold text-foreground">{selectedZone.name}</div><div className="text-sm text-muted-foreground">{selectedZone.physicalPlot}</div></div><span className={cn("rounded-full border px-2.5 py-1 text-xs font-bold", statusColors[selectedZone.status].bg, statusColors[selectedZone.status].border, statusColors[selectedZone.status].text)}>{selectedZone.statusLabel}</span></div></div>{selectedZone.overlaps?.length ? <div className="rounded-lg border border-fuchsia-200 bg-fuchsia-50 p-3 text-sm text-fuchsia-900"><div className="flex items-start gap-2"><Layers className="mt-0.5 size-4" aria-hidden="true" /><span>Nutmeg is selected independently and highlights both P1E and P2W overlay areas without selecting those zones.</span></div></div> : null}<dl className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-card p-3"><dt className="text-xs font-medium text-muted-foreground">Runtime</dt><dd className="mt-1 font-bold text-foreground">{selectedZone.valveOpenTime}</dd></div><div className="rounded-lg bg-card p-3"><dt className="text-xs font-medium text-muted-foreground">Water Pumped</dt><dd className="mt-1 font-bold text-foreground">{formatWaterLitres(selectedZone.totalWaterSupplied)}</dd></div><div className="rounded-lg bg-card p-3"><dt className="text-xs font-medium text-muted-foreground">Per Tree</dt><dd className="mt-1 font-bold text-foreground">{selectedZone.waterPerTree.toLocaleString("en-IN")} L</dd></div><div className="rounded-lg bg-card p-3"><dt className="text-xs font-medium text-muted-foreground">Records</dt><dd className="mt-1 font-bold text-foreground">{selectedZone.recordsCount}</dd></div></dl><div className="rounded-lg border border-border p-3 text-sm"><div className="font-semibold text-foreground">Verified motor / valve mapping</div><ul className="mt-2 list-disc space-y-1 pl-5 text-muted-foreground">{selectedZone.configuredMotorValves.map((mapping) => <li key={mapping}>{mapping}</li>)}</ul></div></div></Panel></div>
}
