"use client"

import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Panel } from "@/components/farm/panel"
import { formatNumberIN, type TrendPoint, type Zone } from "@/lib/irrigation-data"

interface Props { zones: Zone[]; trend: TrendPoint[]; isLoading?: boolean; errorMessage?: string | null }
function fmt(value: unknown, name: unknown): [string, string] { const n = typeof value === "number" ? value : Number(value ?? 0); const label = String(name); if (label.toLowerCase().includes("runtime")) return [`${n.toLocaleString("en-IN")} h`, label]; if (label.toLowerCase().includes("tree")) return [`${formatNumberIN(n)} L/tree`, label]; return [`${formatNumberIN(n)} L`, label] }
function ChartState({ label, wide = false }: { label: string; wide?: boolean }) { return <Panel title="Irrigation Charts" className={wide ? "lg:col-span-2" : undefined}><div className="flex min-h-[260px] items-center justify-center rounded-lg border border-dashed border-border bg-muted/20 p-6 text-center text-sm text-muted-foreground">{label}</div></Panel> }

export function IrrigationChartsHybrid({ zones, trend, isLoading = false, errorMessage = null }: Props) {
  if (isLoading) return <div className="grid gap-4 lg:grid-cols-2"><ChartState label="Loading live chart data..." /><ChartState label="Loading live chart data..." /><ChartState label="Loading live chart data..." wide /></div>
  if (errorMessage) return <ChartState label={errorMessage} wide />
  const runtimeWaterData = zones.map((zone) => ({ zone: zone.abbr, runtimeHours: zone.totalRuntimeHours, waterLitres: zone.totalWaterSupplied }))
  const perTreeData = zones.map((zone) => ({ zone: zone.abbr, waterPerTree: zone.waterPerTree, crop: zone.crop }))
  const hasAnyData = zones.some((zone) => zone.totalRuntimeMinutes > 0) || trend.length > 0
  if (!hasAnyData) return <ChartState label="No live irrigation records for the selected period." wide />
  return <div className="grid grid-cols-1 gap-4 lg:grid-cols-2"><Panel title="Runtime and Water Pumped by Zone"><ResponsiveContainer width="100%" height={310}><BarChart data={runtimeWaterData} margin={{ left: 8, right: 8 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="zone" /><YAxis yAxisId="runtime" label={{ value: "Runtime (hours)", angle: -90, position: "insideLeft" }} /><YAxis yAxisId="water" orientation="right" tickFormatter={(value: number) => formatNumberIN(value)} label={{ value: "Water (L)", angle: 90, position: "insideRight" }} width={88} /><Tooltip formatter={(value, name) => fmt(value, name)} /><Legend /><Bar yAxisId="runtime" dataKey="runtimeHours" fill="#2563eb" name="Runtime (hours)" radius={[4, 4, 0, 0]} /><Bar yAxisId="water" dataKey="waterLitres" fill="#10b981" name="Water Pumped" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></Panel><Panel title="Water Supplied per Tree"><ResponsiveContainer width="100%" height={310}><BarChart data={perTreeData} margin={{ left: 8, right: 8 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="zone" /><YAxis tickFormatter={(value: number) => formatNumberIN(value)} label={{ value: "Litres per tree", angle: -90, position: "insideLeft" }} width={80} /><Tooltip formatter={(value, name) => fmt(value, name)} /><Legend /><Bar dataKey="waterPerTree" fill="#f59e0b" name="Water per Tree" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer><p className="mt-3 text-xs text-muted-foreground">Rates: Coconut 100 L/tree/hour, Nutmeg 80 L/tree/hour, Jackfruit 60 L/tree/hour.</p></Panel><Panel title="Daily Irrigation Trend" className="lg:col-span-2"><ResponsiveContainer width="100%" height={330}><LineChart data={trend} margin={{ left: 8, right: 8 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="displayDate" /><YAxis yAxisId="water" tickFormatter={(value: number) => formatNumberIN(value)} label={{ value: "Water pumped (L)", angle: -90, position: "insideLeft" }} width={90} /><YAxis yAxisId="runtime" orientation="right" label={{ value: "Runtime (hours)", angle: 90, position: "insideRight" }} /><Tooltip formatter={(value, name) => fmt(value, name)} labelFormatter={(label) => `Date: ${label}`} /><Legend /><Line yAxisId="water" type="monotone" dataKey="totalWaterLitres" stroke="#2563eb" name="Water Pumped" strokeWidth={2.5} dot={{ r: 3 }} /><Line yAxisId="runtime" type="monotone" dataKey="totalRuntimeHours" stroke="#16a34a" name="Runtime (hours)" strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></Panel></div>
}

