"use client"

import { useMemo, useState } from "react"
import { ArrowLeft, Check, ChevronRight, CircleDollarSign, ClipboardList, CreditCard, Search, Users, Wallet } from "lucide-react"
import Link from "next/link"
import { DashboardShell } from "@/components/farm/dashboard-shell"
import { calculateWage, dashboardTotals, findWorker, formatRupees, loanBalance, loans, navItems, queries, wageEntries, workers, type WorkerSection } from "@/lib/worker-management-data"

const money = (value: number) => formatRupees(value)

function Stat({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Users }) {
  return <div className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className="size-5 text-primary" aria-hidden="true" /></div><p className="mt-3 font-serif text-3xl font-bold text-foreground">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>
}

function SectionTitle({ title, description }: { title: string; description: string }) { return <div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Muthu Farms · Worker Management</p><h1 className="mt-2 font-serif text-3xl font-bold text-foreground sm:text-4xl">{title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div> }

function Dashboard() {
  return <div className="flex flex-col gap-6"><SectionTitle title="Dashboard" description="A quick view of labour, wages and outstanding worker advances." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active workers" value={String(dashboardTotals.activeWorkers)} detail="Across the farm team" icon={Users} /><Stat label="This week" value={money(dashboardTotals.thisWeek)} detail="Calculated from submitted entries" icon={CircleDollarSign} /><Stat label="Pending settlement" value={money(dashboardTotals.pendingSettlement)} detail="To be reviewed this week" icon={Wallet} /><Stat label="Outstanding loans" value={money(dashboardTotals.outstandingLoans)} detail="Across 3 active advances" icon={CreditCard} /></div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-serif text-xl font-bold">Recent wage activity</h2><span className="text-xs text-muted-foreground">Week ending 08 Aug 2026</span></div><div className="mt-5 flex flex-col gap-3">{wageEntries.slice(0, 4).map((entry) => { const worker = findWorker(entry.workerId)!; return <div key={entry.id} className="flex items-center justify-between border-b border-border pb-3 last:border-0 last:pb-0"><div><p className="font-medium">{worker.name}</p><p className="text-xs text-muted-foreground">{entry.daysWorked} days · {entry.overtimeHours} overtime hours</p></div><div className="text-right"><p className="font-semibold">{money(calculateWage(entry, worker))}</p><span className={entry.status === "Paid" ? "text-xs text-primary" : "text-xs text-warning-foreground"}>{entry.status}</span></div></div> })}</div></div><div className="rounded-xl border border-border bg-card p-5"><h2 className="font-serif text-xl font-bold">Open queries</h2><div className="mt-5 flex flex-col gap-4">{queries.filter((query) => query.status === "Open").map((query) => <div key={query.id} className="flex gap-3"><div className="mt-1 size-2 rounded-full bg-warning" /><div><p className="text-sm font-medium">{query.subject}</p><p className="mt-1 text-xs text-muted-foreground">{query.worker} · {query.date}</p></div></div>)}</div></div></div></div>
}

function WageEntry() {
  const [saved, setSaved] = useState(false)
  return <div><SectionTitle title="Daily Wage Entry" description="Record attendance and adjustments for the current wage week." /><div className="rounded-xl border border-border bg-card p-5"><div className="mb-5 flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-serif text-xl font-bold">Week ending 08 Aug 2026</h2><p className="text-sm text-muted-foreground">Enter days worked, overtime and advances.</p></div><button type="button" onClick={() => setSaved(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{saved ? <Check aria-hidden="true" /> : null}{saved ? "Entries saved" : "Save entries"}</button></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground"><th className="px-3 py-3">Worker</th><th className="px-3 py-3">Daily wage</th><th className="px-3 py-3">Days worked</th><th className="px-3 py-3">Overtime</th><th className="px-3 py-3">Advance</th><th className="px-3 py-3 text-right">Net wage</th></tr></thead><tbody>{wageEntries.map((entry) => { const worker = findWorker(entry.workerId)!; return <tr key={entry.id} className="border-b border-border last:border-0"><td className="px-3 py-4 font-medium">{worker.name}<span className="block text-xs font-normal text-muted-foreground">{worker.role}</span></td><td className="px-3 py-4">{money(worker.dailyWage)}</td><td className="px-3 py-4"><input aria-label={`${worker.name} days worked`} defaultValue={entry.daysWorked} type="number" min="0" max="7" className="w-20 rounded-md border border-input bg-background px-2 py-2" /></td><td className="px-3 py-4"><input aria-label={`${worker.name} overtime hours`} defaultValue={entry.overtimeHours} type="number" min="0" className="w-20 rounded-md border border-input bg-background px-2 py-2" /></td><td className="px-3 py-4"><input aria-label={`${worker.name} advance`} defaultValue={entry.advance} type="number" min="0" className="w-24 rounded-md border border-input bg-background px-2 py-2" /></td><td className="px-3 py-4 text-right font-semibold">{money(calculateWage(entry, worker))}</td></tr> })}</tbody></table></div></div></div>
}

function Directory() { const [search, setSearch] = useState(""); const filtered = workers.filter((worker) => `${worker.name} ${worker.role}`.toLowerCase().includes(search.toLowerCase())); return <div><SectionTitle title="Worker Directory" description="The local register of people working across Muthu Farms." /><div className="rounded-xl border border-border bg-card p-5"><label className="relative block max-w-sm"><span className="sr-only">Search workers</span><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" aria-hidden="true" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or role" className="w-full rounded-lg border border-input bg-background py-2 pl-9 pr-3 text-sm" /></label><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((worker) => <div key={worker.id} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between"><div><p className="font-semibold">{worker.name}</p><p className="mt-1 text-sm text-muted-foreground">{worker.role}</p></div><span className={worker.status === "Active" ? "rounded-full bg-accent px-2 py-1 text-xs text-accent-foreground" : "rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground"}>{worker.status}</span></div><div className="mt-4 flex justify-between text-xs text-muted-foreground"><span>{worker.phone}</span><span>{money(worker.dailyWage)} / day</span></div></div>)}</div></div></div> }

function Settlement() { return <div><SectionTitle title="Weekly Settlement" description="Review the calculated wage total before marking the week as settled." /><div className="rounded-xl border border-border bg-card p-5"><div className="flex flex-col gap-2 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-muted-foreground">Week ending</p><p className="font-serif text-2xl font-bold">08 Aug 2026</p></div><p className="font-serif text-3xl font-bold text-primary">{money(dashboardTotals.thisWeek)}</p></div><div className="mt-4 flex flex-col gap-3">{wageEntries.map((entry) => { const worker = findWorker(entry.workerId)!; return <div key={entry.id} className="flex items-center justify-between rounded-lg bg-muted/50 p-3"><span className="text-sm font-medium">{worker.name}</span><span className="text-sm font-semibold">{money(calculateWage(entry, worker))}</span></div> })}</div><button type="button" className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Mark week as settled</button></div></div> }

function Loans() { return <div><SectionTitle title="Loan Register" description="Track worker advances and the remaining balance for each loan." /><div className="rounded-xl border border-border bg-card p-5"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground"><th className="px-3 py-3">Worker</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">Purpose</th><th className="px-3 py-3">Loan</th><th className="px-3 py-3">Repaid</th><th className="px-3 py-3 text-right">Balance</th></tr></thead><tbody>{loans.map((loan) => <tr key={loan.id} className="border-b border-border last:border-0"><td className="px-3 py-4 font-medium">{findWorker(loan.workerId)?.name}</td><td className="px-3 py-4 text-muted-foreground">{loan.date}</td><td className="px-3 py-4">{loan.note}</td><td className="px-3 py-4">{money(loan.amount)}</td><td className="px-3 py-4">{money(loan.repaid)}</td><td className="px-3 py-4 text-right font-semibold">{money(loanBalance(loan))}</td></tr>)}</tbody></table></div></div></div> }

function Query() { return <div><SectionTitle title="Query" description="Keep worker questions visible until they are answered and recorded." /><div className="flex flex-col gap-3">{queries.map((query) => <div key={query.id} className="flex flex-col gap-3 rounded-xl border border-border bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-semibold">{query.subject}</p><span className={query.status === "Open" ? "rounded-full bg-warning/30 px-2 py-1 text-xs text-warning-foreground" : "rounded-full bg-accent px-2 py-1 text-xs text-accent-foreground"}>{query.status}</span></div><p className="mt-1 text-sm text-muted-foreground">{query.worker} · raised {query.date}</p></div><button type="button" className="inline-flex items-center gap-1 self-start text-sm font-semibold text-primary sm:self-auto">View query <ChevronRight className="size-4" aria-hidden="true" /></button></div>)}</div></div> }

export function WorkerManagementClient() { const [section, setSection] = useState<WorkerSection>("Dashboard"); const content = useMemo(() => ({ Dashboard: <Dashboard />, "Daily Wage Entry": <WageEntry />, "Worker Directory": <Directory />, "Weekly Settlement": <Settlement />, "Loan Register": <Loans />, Query: <Query /> })[section], [section]); return <DashboardShell><div className="min-h-screen bg-background"><div className="border-b border-border bg-card"><div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-5 sm:px-6"><Link href="/" className="rounded-lg border border-border p-2 text-muted-foreground hover:text-foreground" aria-label="Back to farm home"><ArrowLeft className="size-5" aria-hidden="true" /></Link><div><p className="font-serif text-xl font-bold">Worker Management</p><p className="text-xs text-muted-foreground">Local Phase 1 workspace · seeded data</p></div></div><nav aria-label="Worker management sections" className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 pb-3 sm:px-6">{navItems.map((item) => <button key={item} type="button" onClick={() => setSection(item)} aria-current={section === item ? "page" : undefined} className={section === item ? "whitespace-nowrap rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground" : "whitespace-nowrap rounded-lg px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground"}>{item}</button>)}</nav></div><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">{content}</main></div></DashboardShell> }

export function WorkerManagementPage() { return <WorkerManagementClient /> }

// Kept in this client module so Phase 1 never reaches an external service.
void ClipboardList
