// Company assignments from the owner-supplied beetle-in-traps workbook.
// Workbook SHA-256: a123dcdab5c11397c0cc6a2ea7ce5e0733e49a6e6026c6ac8a350fac7fa4c483
// Plot/species: production backend beetle_trap.py blob da45e443b9d347fe4bd6a3d81753c289cc4d3923.
export const BEETLE_LURE_START_DATE = "2026-09-24"
export const BEETLE_LURE_ASSIGNMENTS = [
  ["1", 1, "Red Palm Weevil", "B"],
  ["2", 1, "Rhinoceros Beetle", "B"],
  ["3", 1, "Red Palm Weevil", "G"],
  ["4", 1, "Rhinoceros Beetle", "G"],
  ["5", 1, "Rhinoceros Beetle", "B"],
  ["6", 1, "Red Palm Weevil", "B"],
  ["7", 1, "Red Palm Weevil", "G"],
  ["8", 1, "Rhinoceros Beetle", "G"],
  ["9", 1, "Red Palm Weevil", "B"],
  ["10", 1, "Rhinoceros Beetle", "B"],
  ["11", 1, "Red Palm Weevil", "G"],
  ["12", 1, "Rhinoceros Beetle", "G"],
  ["13", 1, "Red Palm Weevil", "B"],
  ["14", 1, "Rhinoceros Beetle", "B"],
  ["15", 1, "Red Palm Weevil", "G"],
  ["16", 1, "Rhinoceros Beetle", "G"],
  ["17", 1, "Rhinoceros Beetle", "B"],
  ["18", 1, "Red Palm Weevil", "B"],
  ["19", 1, "Red Palm Weevil", "G"],
  ["20", 1, "Red Palm Weevil", "B"],
  ["21", 1, "Rhinoceros Beetle", "G"],
  ["22", 1, "Rhinoceros Beetle", "B"],
  ["23", 1, "Red Palm Weevil", "G"],
  ["24", 1, "Red Palm Weevil", "B"],
  ["25", 1, "Red Palm Weevil", "G"],
  ["26", 1, "Red Palm Weevil", "B"],
  ["27", 1, "Red Palm Weevil", "G"],
  ["28", 1, "Rhinoceros Beetle", "G"],
  ["29", 1, "Rhinoceros Beetle", "B"],
  ["30", 1, "Rhinoceros Beetle", "G"],
  ["31", 1, "Red Palm Weevil", "B"],
  ["32", 1, "Red Palm Weevil", "G"],
  ["33", 1, "Red Palm Weevil", "B"],
  ["34", 1, "Rhinoceros Beetle", "B"],
  ["35", 1, "Red Palm Weevil", "G"],
  ["36", 2, "Red Palm Weevil", "B"],
  ["37", 2, "Rhinoceros Beetle", "G"],
  ["38", 2, "Red Palm Weevil", "G"],
  ["39", 1, "Rhinoceros Beetle", "B"],
  ["40", 2, "Red Palm Weevil", "B"],
  ["41", 2, "Rhinoceros Beetle", "G"],
  ["42", 2, "Red Palm Weevil", "G"],
  ["43", 2, "Rhinoceros Beetle", "B"],
  ["44", 2, "Red Palm Weevil", "B"],
  ["45", 2, "Rhinoceros Beetle", "G"],
  ["46", 2, "Red Palm Weevil", "G"],
  ["47", 2, "Rhinoceros Beetle", "B"],
  ["48", 2, "Rhinoceros Beetle", "G"],
  ["49", 2, "Red Palm Weevil", "B"],
  ["50", 2, "Rhinoceros Beetle", "B"],
  ["51", 2, "Red Palm Weevil", "G"],
  ["52", 2, "Red Palm Weevil", "B"],
  ["53", 2, "Rhinoceros Beetle", "G"],
  ["54", 2, "Red Palm Weevil", "G"],
  ["55", 2, "Rhinoceros Beetle", "B"],
  ["56", 2, "Red Palm Weevil", "B"],
  ["57", 2, "Rhinoceros Beetle", "G"],
  ["58", 2, "Rhinoceros Beetle", "B"],
  ["59", 2, "Rhinoceros Beetle", "G"],
  ["60", 2, "Red Palm Weevil", "G"],
  ["61", 2, "Rhinoceros Beetle", "B"],
  ["62", 2, "Rhinoceros Beetle", "G"],
  ["63", 2, "Rhinoceros Beetle", "B"],
  ["64", 2, "Red Palm Weevil", "B"],
  ["65", 2, "Rhinoceros Beetle", "G"],
  ["66", 2, "Red Palm Weevil", "G"],
  ["67", 2, "Rhinoceros Beetle", "B"],
  ["68", 2, "Rhinoceros Beetle", "G"],
  ["69", 2, "Red Palm Weevil", "B"],
  ["70", 2, "Rhinoceros Beetle", "B"],
  ["71", 2, "Red Palm Weevil", "G"],
  ["72", 2, "Rhinoceros Beetle", "G"],
  ["73", 2, "Red Palm Weevil", "B"],
  ["74", 2, "Rhinoceros Beetle", "B"],
  ["75", 2, "Red Palm Weevil", "G"],
  ["76", 2, "Rhinoceros Beetle", "G"],
  ["77", 2, "Red Palm Weevil", "B"],
  ["78", 2, "Rhinoceros Beetle", "B"],
] as const
