-- MFMS Inventory schema foundation
-- Phase 2 migration design only.
--
-- Approved source for later import:
--   INVENTORY_APPROVED_IMPORT_PREVIEW.xlsx
--
-- Approved future opening-stock transaction date:
--   2026-07-13
--
-- This migration creates inventory master/ledger tables and a stock-balance view.
-- It does NOT import product-master records or opening-stock transactions.

begin;

create table if not exists inventory_categories (
    id bigint generated by default as identity primary key,
    category_name text not null,
    description text null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text null,
    updated_by text null,

    constraint inventory_categories_name_not_blank_check
        check (length(btrim(category_name)) > 0)
);

create unique index if not exists idx_inventory_categories_name_ci
    on inventory_categories (lower(btrim(category_name)));

create table if not exists inventory_subcategories (
    id bigint generated by default as identity primary key,
    category_id bigint not null
        references inventory_categories(id)
        on update cascade
        on delete restrict,
    subcategory_name text not null,
    description text null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text null,
    updated_by text null,

    constraint inventory_subcategories_name_not_blank_check
        check (length(btrim(subcategory_name)) > 0)
);

create unique index if not exists idx_inventory_subcategories_category_name_ci
    on inventory_subcategories (category_id, lower(btrim(subcategory_name)));

create unique index if not exists idx_inventory_subcategories_category_id_id
    on inventory_subcategories (category_id, id);

create index if not exists idx_inventory_subcategories_category_id
    on inventory_subcategories (category_id);

create table if not exists inventory_products (
    id bigint generated by default as identity primary key,
    product_name text not null,
    original_product_name text null,
    category_id bigint not null
        references inventory_categories(id)
        on update cascade
        on delete restrict,
    subcategory_id bigint not null
        references inventory_subcategories(id)
        on update cascade
        on delete restrict,
    base_unit text not null,
    reorder_level numeric(14, 3) null,
    expiry_required boolean not null default false,
    active boolean not null default true,
    remarks text null,
    source text not null default 'Manual_Admin',
    source_reference text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text null,
    updated_by text null,

    constraint inventory_products_name_not_blank_check
        check (length(btrim(product_name)) > 0),

    constraint inventory_products_base_unit_check
        check (base_unit in ('kg', 'g', 'L', 'ml', 'number', 'to_confirm')),

    constraint inventory_products_reorder_level_check
        check (reorder_level is null or reorder_level >= 0),

    constraint inventory_products_source_check
        check (source in ('Manual_Admin', 'INITIAL_EXCEL_IMPORT', 'ODK', 'Import', 'System')),

    constraint inventory_products_subcategory_matches_category_fk
        foreign key (category_id, subcategory_id)
        references inventory_subcategories(category_id, id)
        on update cascade
        on delete restrict
);

create unique index if not exists idx_inventory_products_name_ci
    on inventory_products (lower(btrim(product_name)));

create unique index if not exists idx_inventory_products_source_reference
    on inventory_products (source, source_reference)
    where source_reference is not null;

create index if not exists idx_inventory_products_category_subcategory
    on inventory_products (category_id, subcategory_id);

create index if not exists idx_inventory_products_active
    on inventory_products (active);

create table if not exists inventory_transactions (
    id bigint generated by default as identity primary key,
    product_id bigint not null
        references inventory_products(id)
        on update cascade
        on delete restrict,
    transaction_date date not null,
    transaction_type text not null,
    quantity numeric(14, 3) not null,
    quantity_delta numeric(14, 3) generated always as (
        case
            when transaction_type in (
                'OPENING_STOCK',
                'PURCHASE',
                'RETURN_IN',
                'ADJUSTMENT_INCREASE'
            ) then quantity
            when transaction_type in (
                'USAGE',
                'WASTE_EXPIRED',
                'ADJUSTMENT_DECREASE'
            ) then -quantity
            else 0
        end
    ) stored,
    unit text not null,
    expiry_date date null,
    batch_no text null,
    supplier text null,
    reference_no text null,
    invoice_no text null,
    purpose text null,
    plot_zone text null,
    crop text null,
    source text not null default 'Manual_Admin',
    source_reference text null,
    entered_by text null,
    remarks text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text null,
    updated_by text null,

    constraint inventory_transactions_type_check
        check (transaction_type in (
            'OPENING_STOCK',
            'PURCHASE',
            'USAGE',
            'RETURN_IN',
            'WASTE_EXPIRED',
            'ADJUSTMENT_INCREASE',
            'ADJUSTMENT_DECREASE'
        )),

    constraint inventory_transactions_quantity_positive_check
        check (quantity > 0),

    constraint inventory_transactions_unit_check
        check (unit in ('kg', 'g', 'L', 'ml', 'number')),

    constraint inventory_transactions_source_check
        check (source in ('Manual_Admin', 'INITIAL_EXCEL_IMPORT', 'ODK', 'Import', 'System')),

    constraint inventory_transactions_usage_details_required_check
        check (
            transaction_type <> 'USAGE'
            or (
                purpose is not null
                and length(btrim(purpose)) > 0
                and plot_zone is not null
                and length(btrim(plot_zone)) > 0
                and crop is not null
                and length(btrim(crop)) > 0
            )
        )
);

create index if not exists idx_inventory_transactions_product_date
    on inventory_transactions (product_id, transaction_date desc, id desc);

create index if not exists idx_inventory_transactions_type_date
    on inventory_transactions (transaction_type, transaction_date desc, id desc);

create unique index if not exists idx_inventory_transactions_source_reference
    on inventory_transactions (source, source_reference)
    where source_reference is not null;

create index if not exists idx_inventory_transactions_expiry_date
    on inventory_transactions (expiry_date)
    where expiry_date is not null;

create index if not exists idx_inventory_transactions_invoice_no
    on inventory_transactions (invoice_no)
    where invoice_no is not null;

create or replace function inventory_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_inventory_categories_set_updated_at on inventory_categories;
create trigger trg_inventory_categories_set_updated_at
before update on inventory_categories
for each row
execute function inventory_set_updated_at();

drop trigger if exists trg_inventory_subcategories_set_updated_at on inventory_subcategories;
create trigger trg_inventory_subcategories_set_updated_at
before update on inventory_subcategories
for each row
execute function inventory_set_updated_at();

drop trigger if exists trg_inventory_products_set_updated_at on inventory_products;
create trigger trg_inventory_products_set_updated_at
before update on inventory_products
for each row
execute function inventory_set_updated_at();

drop trigger if exists trg_inventory_transactions_set_updated_at on inventory_transactions;
create trigger trg_inventory_transactions_set_updated_at
before update on inventory_transactions
for each row
execute function inventory_set_updated_at();

create or replace function inventory_validate_transaction_master_data()
returns trigger
language plpgsql
as $$
declare
    v_product_name text;
    v_base_unit text;
    v_active boolean;
begin
    select product_name, base_unit, active
      into v_product_name, v_base_unit, v_active
      from inventory_products
     where id = new.product_id;

    if not found then
        raise exception 'Inventory product_id % does not exist', new.product_id
            using errcode = '23503';
    end if;

    if v_active is not true then
        raise exception 'Inventory product % is inactive and cannot receive transactions', v_product_name
            using errcode = '23514';
    end if;

    if v_base_unit = 'to_confirm' then
        raise exception 'Inventory product % has base_unit to_confirm; confirm base unit before transactions', v_product_name
            using errcode = '23514';
    end if;

    if new.unit <> v_base_unit then
        raise exception 'Inventory transaction unit % does not match product base_unit % for product %',
            new.unit,
            v_base_unit,
            v_product_name
            using errcode = '23514';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_inventory_transactions_validate_master_data
    on inventory_transactions;

create trigger trg_inventory_transactions_validate_master_data
before insert or update on inventory_transactions
for each row
execute function inventory_validate_transaction_master_data();

create or replace function inventory_prevent_negative_stock()
returns trigger
language plpgsql
as $$
declare
    v_product_ids bigint[];
    v_product_id bigint;
    v_balance numeric(14, 3);
begin
    if tg_op = 'DELETE' then
        v_product_ids := array[old.product_id];
    elsif tg_op = 'UPDATE' then
        v_product_ids := array(
            select distinct unnest(array[old.product_id, new.product_id])
        );
    else
        v_product_ids := array[new.product_id];
    end if;

    foreach v_product_id in array v_product_ids loop
        perform pg_advisory_xact_lock(v_product_id);

        select coalesce(sum(quantity_delta), 0)
          into v_balance
          from inventory_transactions
         where product_id = v_product_id;

        if v_balance < 0 then
            raise exception
                'Inventory transaction would create negative stock for product_id %. Resulting balance %',
                v_product_id,
                v_balance
                using errcode = '23514';
        end if;
    end loop;

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_inventory_transactions_no_negative_stock
    on inventory_transactions;

create trigger trg_inventory_transactions_no_negative_stock
after insert or update or delete on inventory_transactions
for each row
execute function inventory_prevent_negative_stock();

create or replace view vw_inventory_stock_balance as
select
    p.id as product_id,
    p.product_name,
    p.original_product_name,
    c.category_name,
    s.subcategory_name,
    p.base_unit,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'OPENING_STOCK'
    ), 0)::numeric(14, 3) as opening_stock,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'PURCHASE'
    ), 0)::numeric(14, 3) as purchased,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'RETURN_IN'
    ), 0)::numeric(14, 3) as returned_in,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'USAGE'
    ), 0)::numeric(14, 3) as used,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'WASTE_EXPIRED'
    ), 0)::numeric(14, 3) as wasted_expired,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'ADJUSTMENT_INCREASE'
    ), 0)::numeric(14, 3) as adjustment_in,
    coalesce(sum(t.quantity) filter (
        where t.transaction_type = 'ADJUSTMENT_DECREASE'
    ), 0)::numeric(14, 3) as adjustment_out,
    coalesce(sum(t.quantity_delta), 0)::numeric(14, 3) as current_stock,
    max(t.transaction_date) as latest_transaction_date,
    max(t.created_at) as latest_transaction_created_at,
    min(t.expiry_date) filter (
        where t.expiry_date is not null
          and t.quantity_delta > 0
          and t.expiry_date >= current_date
    ) as nearest_unexpired_expiry_date,
    coalesce(
        bool_or(t.expiry_date is not null and t.expiry_date < current_date),
        false
    ) as has_expired_lot_history,
    p.active
from inventory_products p
join inventory_categories c
  on c.id = p.category_id
join inventory_subcategories s
  on s.id = p.subcategory_id
left join inventory_transactions t
  on t.product_id = p.id
group by
    p.id,
    p.product_name,
    p.original_product_name,
    c.category_name,
    s.subcategory_name,
    p.base_unit,
    p.active;

commit;
